ws_server:
  host: 'localhost'
  port: 9001

user:
  login: 'SimpleAI1'
  password: 'chubaka'
  is_creator: true

game:
  name: 'AiGame'
  map: 'AiMap'
  army: 'AiArmy'

  tactic: {
    Bomb:        [1, 10, 14, 16],
    Flag:        [0],
    Spy:         [3],
    Scout:       [11, 15, 17, 19],
    Miner:       [13, 18],
    Sergeant:    [8],
    Lieutenant:  [6],
    Captain:     [9],
    Major:       [4],
    Colonel:     [7, 12],
    General:     [5],
    Marshal:     [2]
  }

log_file: 'simple_ai_1.log'
game_process_file: 'simple_ai_1_game.txt'
