ws_server:
  host: 'localhost'
  port: 9001

user:
  login: 'SimpleAI'
  password: 'chubaka'
  is_creator: false

game:
  name: 'ClassicalGame'
  map: 'ClassicalMap'
  army: 'ClassicalArmy'

  tactic: 'ScoutGambit'
  prepared_moves: []

log_file: 'simple_ai.log'
