ws_server:
  host: 'localhost'
  port: 9001

user:
  login: 'SimpleAI1'
  password: 'chubaka'
  is_creator: true

game:
  name: 'ClassicalGame'
  map: 'ClassicalMap'
  army: 'ClassicalArmy'

  tactic: {
    Flag:        [0],
    Bomb:        [1, 10, 14, 19, 21, 26],
    Spy:         [17],
    Scout:       [4, 7, 9, 24, 27, 30, 34, 39],
    Miner:       [3, 5, 12, 18, 36],
    Sergeant:    [2, 13, 22, 33],
    Lieutenant:  [6, 8, 16, 31],
    Captain:     [11, 29, 35, 37],
    Major:       [15, 20, 38],
    Colonel:     [23, 32],
    General:     [28],
    Marshal:     [25]
  }

  prepared_moves: []

log_file: 'simple_ai_1.log'
