ws_server:
  host: 'localhost'
  port: 9001

user:
  login: 'SimpleAI2'
  password: 'chubaka'
  is_creator: false

game:
  name: 'AiGame'
  map: 'AiMap'
  army: 'AiArmy'

  tactic: {
    Bomb:        [1, 7, 10, 17],
    Flag:        [0],
    Spy:         [2],
    Scout:       [13, 14, 15, 18],
    Miner:       [9, 16],
    Sergeant:    [12],
    Lieutenant:  [6],
    Captain:     [4],
    Major:       [8],
    Colonel:     [5, 11],
    General:     [19],
    Marshal:     [3],
  }

  prepared_moves: []

log_file: 'simple_ai_2.log'
